# Generated by Django 3.1.2 on 2020-10-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('column_name_1', models.CharField(max_length=50)),
                ('column_name_2', models.CharField(max_length=50)),
            ],
        ),
    ]
