# Generated by Django 3.1.2 on 2020-10-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
